"""Generated by scripts/vendor.py -- do not edit."""

UPSTREAM_REPO = "https://github.com/delyan-boychev/disentangled-flash"
UPSTREAM_REF = "8e2844d"
UPSTREAM_COMMIT = "8e2844d07ff57b56d015c45bacd74f0bee64d641"
