"""Generated by scripts/vendor.py -- do not edit."""

UPSTREAM_REPO = "https://github.com/delyan-boychev/disentangled-flash"
UPSTREAM_REF = "d3c68e6"
UPSTREAM_COMMIT = "d3c68e60ef7426679a8e4dc226877beeb6e37382"
