"""Generated by scripts/vendor.py -- do not edit."""

UPSTREAM_REPO = "https://github.com/delyan-boychev/disentangled-flash"
UPSTREAM_REF = "v0.2.0"
UPSTREAM_COMMIT = "d4e0fd48857e318bebc6be80dc104bac673bbd5c"
