#!/usr/bin/env python3
"""Vendor the Triton implementation from the standalone disentangled-flash repo.

Hub kernels may only import from the standard library, torch, or the kernel
itself, so this kernel cannot depend on the ``disentangled-flash`` PyPI
package. This script copies the implementation modules from a pinned upstream
git ref into ``torch-ext/disentangled_flash/`` verbatim.

The copied modules already use relative intra-package imports and pull in
nothing beyond stdlib/torch/triton, so no rewriting is required. The script
verifies both properties and fails loudly if upstream ever breaks them.

Usage:
    python scripts/vendor.py --source ../disentangled-flash --ref v0.2.0
"""

from __future__ import annotations

import argparse
import ast
import subprocess
import sys
from pathlib import Path

# Implementation modules copied verbatim from upstream.
VENDORED_MODULES = (
    "_reference.py",  # auditable HF DeBERTa reference (Apache-2.0, see NOTICE)
    "_torch.py",
    "_validation.py",
    "kernel.py",
    "packed.py",
    "position.py",
    "tuning.py",
    "profiles/__init__.py",
)

# Deliberately NOT vendored:
#   deberta.py  -> replaced by the stateless _encoder.py adapter
#   tune.py     -> offline tuning CLI, stays a standalone power-user tool
#   __init__.py -> the kernel defines its own public surface

ALLOWED_TOP_LEVEL_IMPORTS = {"torch", "triton"}
STDLIB = set(sys.stdlib_module_names)

UPSTREAM_REPO = "https://github.com/delyan-boychev/disentangled-flash"


def _git(source: Path, *args: str) -> str:
    return subprocess.run(
        ["git", "-C", str(source), *args],
        capture_output=True,
        text=True,
        check=True,
    ).stdout


def _external_imports(path: Path) -> set[str]:
    """Top-level non-stdlib, non-relative modules imported by ``path``."""
    tree = ast.parse(path.read_text(), filename=str(path))
    found: set[str] = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            found.update(alias.name.split(".")[0] for alias in node.names)
        elif isinstance(node, ast.ImportFrom):
            if node.level:  # relative import, stays inside the kernel
                continue
            if node.module:
                found.add(node.module.split(".")[0])
    return {name for name in found if name not in STDLIB}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, required=True, help="path to the standalone repo")
    parser.add_argument("--ref", default="v0.2.0", help="upstream git ref to vendor from")
    parser.add_argument(
        "--dest",
        type=Path,
        default=Path(__file__).resolve().parent.parent / "torch-ext" / "disentangled_flash",
    )
    args = parser.parse_args()

    source = args.source.resolve()
    if not (source / ".git").exists():
        print(f"error: {source} is not a git repository", file=sys.stderr)
        return 1

    commit = _git(source, "rev-parse", f"{args.ref}^{{commit}}").strip()
    tracked = set(_git(source, "ls-tree", "-r", "--name-only", args.ref).splitlines())
    failures: list[str] = []

    for name in VENDORED_MODULES:
        upstream_path = f"src/disentangled_flash/{name}"
        if upstream_path not in tracked:
            failures.append(f"{name}: not present at {args.ref}")
            continue
        blob = _git(source, "show", f"{args.ref}:{upstream_path}")
        dest = args.dest / name
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(blob)

        unexpected = _external_imports(dest) - ALLOWED_TOP_LEVEL_IMPORTS
        if unexpected:
            failures.append(f"{name}: disallowed imports {sorted(unexpected)}")
        print(f"  vendored {name:24s} {len(blob.splitlines()):>5d} lines")

    # Tuning profiles ship with the kernel via build.toml `pyext = [..., "json"]`.
    profiles = sorted(
        path
        for path in tracked
        if path.startswith("src/disentangled_flash/profiles/") and path.endswith(".json")
    )
    for path in profiles:
        blob = _git(source, "show", f"{args.ref}:{path}")
        dest = args.dest / "profiles" / Path(path).name
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(blob)
        print(f"  vendored profiles/{Path(path).name[:40]:40s} {len(blob) // 1024:>4d} KiB")

    (args.dest / "_vendored.py").write_text(
        '"""Generated by scripts/vendor.py -- do not edit."""\n\n'
        f'UPSTREAM_REPO = "{UPSTREAM_REPO}"\n'
        f'UPSTREAM_REF = "{args.ref}"\n'
        f'UPSTREAM_COMMIT = "{commit}"\n'
    )
    print(f"  stamped  _vendored.py         {args.ref} @ {commit[:12]}")

    if failures:
        print("\nVENDORING FAILED:", file=sys.stderr)
        for failure in failures:
            print(f"  {failure}", file=sys.stderr)
        return 1
    print(f"\nOK: {len(VENDORED_MODULES)} modules + {len(profiles)} profiles from {args.ref}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
